authors:
  Alex:
    name: Alex The Creator
    description: Creator
    avatar: https://al666ex.pages.dev/img/favicon.ico
  PAlex:
    name: Alex The Pain
    description: Pain
    avatar: https://al666ex.pages.dev/img/pa.png
